create table holiday (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	country VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	price NUMERIC(7,2) NOT NULL
);
insert into holiday (id, country, city, price) values (1, 'Greece', 'Féres', 4535.56);
insert into holiday (id, country, city, price) values (2, 'Russia', 'Kamensk-Shakhtinskiy', 6768.68);
insert into holiday (id, country, city, price) values (3, 'Finland', 'Vaasa', 9692.45);
insert into holiday (id, country, city, price) values (4, 'Russia', 'Otradnoye', 8300.72);
insert into holiday (id, country, city, price) values (5, 'Greece', 'Galatás', 9919.75);
insert into holiday (id, country, city, price) values (6, 'Slovenia', 'Mežica', 1073.29);
insert into holiday (id, country, city, price) values (7, 'Indonesia', 'Woloara', 1310.74);
insert into holiday (id, country, city, price) values (8, 'Afghanistan', 'Farah', 994.85);
insert into holiday (id, country, city, price) values (9, 'Japan', 'Tanushimarumachi-toyoki', 2237.62);
insert into holiday (id, country, city, price) values (10, 'Sweden', 'Karlskoga', 5977.99);
insert into holiday (id, country, city, price) values (11, 'South Africa', 'Kutloanong', 2769.38);
insert into holiday (id, country, city, price) values (12, 'Indonesia', 'Pogag', 5935.02);
insert into holiday (id, country, city, price) values (13, 'China', 'Bailang', 5974.7);
insert into holiday (id, country, city, price) values (14, 'Poland', 'Oksa', 2585.52);
insert into holiday (id, country, city, price) values (15, 'Indonesia', 'Oitui', 2407.61);
insert into holiday (id, country, city, price) values (16, 'Sweden', 'Anderstorp', 2330.83);
insert into holiday (id, country, city, price) values (17, 'China', 'Hetang', 7479.09);
insert into holiday (id, country, city, price) values (18, 'Albania', 'Kukur', 3519.74);
insert into holiday (id, country, city, price) values (19, 'Canada', 'Metchosin', 3614.86);
insert into holiday (id, country, city, price) values (20, 'Brazil', 'Itaberaí', 5937.42);
insert into holiday (id, country, city, price) values (21, 'Czech Republic', 'Hradec Králové', 4658.53);
insert into holiday (id, country, city, price) values (22, 'Malaysia', 'Rawang', 7847.25);
insert into holiday (id, country, city, price) values (23, 'Indonesia', 'Bontang Baru', 3873.11);
insert into holiday (id, country, city, price) values (24, 'United States', 'Sterling', 2703.53);
insert into holiday (id, country, city, price) values (25, 'Russia', 'Ust’-Izhora', 3573.83);
insert into holiday (id, country, city, price) values (26, 'Sweden', 'Ljungby', 6877.58);
insert into holiday (id, country, city, price) values (27, 'Philippines', 'Eguia', 2214.94);
insert into holiday (id, country, city, price) values (28, 'Kenya', 'Mbale', 2913.22);
insert into holiday (id, country, city, price) values (29, 'Russia', 'Mel’nikovo', 8486.72);
insert into holiday (id, country, city, price) values (30, 'Philippines', 'Bagumbayan', 2448.77);
insert into holiday (id, country, city, price) values (31, 'Sweden', 'Huddinge', 9405.64);
insert into holiday (id, country, city, price) values (32, 'Brazil', 'Piritiba', 6467.42);
insert into holiday (id, country, city, price) values (33, 'Czech Republic', 'Červenka', 1838.32);
insert into holiday (id, country, city, price) values (34, 'Indonesia', 'Cigintung', 5143.27);
insert into holiday (id, country, city, price) values (35, 'Indonesia', 'Karanggedang', 9234.67);
insert into holiday (id, country, city, price) values (36, 'China', 'Changning', 1392.32);
insert into holiday (id, country, city, price) values (37, 'Sweden', 'Stockholm', 9852.84);
insert into holiday (id, country, city, price) values (38, 'China', 'Zhouji', 528.35);
insert into holiday (id, country, city, price) values (39, 'China', 'Gaoqiao', 136.76);
insert into holiday (id, country, city, price) values (40, 'Croatia', 'Žrnovo', 8050.41);
insert into holiday (id, country, city, price) values (41, 'Morocco', 'Fezna', 1071.0);
insert into holiday (id, country, city, price) values (42, 'Japan', 'Miharu', 1301.9);
insert into holiday (id, country, city, price) values (43, 'Netherlands', 'Almere Stad', 899.64);
insert into holiday (id, country, city, price) values (44, 'Greece', 'Kimméria', 5413.63);
insert into holiday (id, country, city, price) values (45, 'China', 'Mutangyuan', 4869.8);
insert into holiday (id, country, city, price) values (46, 'China', 'Jinan', 6751.08);
insert into holiday (id, country, city, price) values (47, 'Slovenia', 'Lavrica', 4643.95);
insert into holiday (id, country, city, price) values (48, 'Chile', 'Corral', 8171.9);
insert into holiday (id, country, city, price) values (49, 'Afghanistan', 'Kai', 6781.9);
insert into holiday (id, country, city, price) values (50, 'China', 'Liji', 9602.28);
insert into holiday (id, country, city, price) values (51, 'Hungary', 'Nyíregyháza', 1182.15);
insert into holiday (id, country, city, price) values (52, 'Indonesia', 'Sukamanah', 5444.05);
insert into holiday (id, country, city, price) values (53, 'Indonesia', 'Krajan Curahcotok', 7808.72);
insert into holiday (id, country, city, price) values (54, 'United States', 'Sacramento', 4614.57);
insert into holiday (id, country, city, price) values (55, 'Indonesia', 'Dukuhmencek Lor', 8012.0);
insert into holiday (id, country, city, price) values (56, 'Japan', 'Sendai', 5324.16);
insert into holiday (id, country, city, price) values (57, 'Albania', 'Kokaj', 3607.16);
insert into holiday (id, country, city, price) values (58, 'Saint Vincent and the Grenadines', 'Port Elizabeth', 7111.92);
insert into holiday (id, country, city, price) values (59, 'Mexico', 'Benito Juarez', 8063.87);
insert into holiday (id, country, city, price) values (60, 'Brazil', 'Piuí', 1440.73);
insert into holiday (id, country, city, price) values (61, 'Philippines', 'Aurora', 6629.66);
insert into holiday (id, country, city, price) values (62, 'China', 'Liugong', 7847.3);
insert into holiday (id, country, city, price) values (63, 'Indonesia', 'Habingkloang', 3321.57);
insert into holiday (id, country, city, price) values (64, 'Portugal', 'Sobreira', 366.44);
insert into holiday (id, country, city, price) values (65, 'China', 'Sicheng', 5154.29);
insert into holiday (id, country, city, price) values (66, 'China', 'Zaoshi', 1540.91);
insert into holiday (id, country, city, price) values (67, 'China', 'Xingquan', 5157.46);
insert into holiday (id, country, city, price) values (68, 'China', 'Jinrui', 2689.3);
insert into holiday (id, country, city, price) values (69, 'Peru', 'San Buenaventura', 4961.35);
insert into holiday (id, country, city, price) values (70, 'Indonesia', 'Kota Ternate', 8399.85);
insert into holiday (id, country, city, price) values (71, 'China', 'Xinbu', 5006.84);
insert into holiday (id, country, city, price) values (72, 'Greece', 'Néa Filadélfeia', 6165.53);
insert into holiday (id, country, city, price) values (73, 'Uganda', 'Nyachera', 8128.66);
insert into holiday (id, country, city, price) values (74, 'Philippines', 'Mandangoa', 4135.54);
insert into holiday (id, country, city, price) values (75, 'Guatemala', 'Jutiapa', 6873.02);
insert into holiday (id, country, city, price) values (76, 'Indonesia', 'Lela', 7436.23);
insert into holiday (id, country, city, price) values (77, 'Vietnam', 'Đưc Trọng', 1510.52);
insert into holiday (id, country, city, price) values (78, 'Canada', 'Vulcan', 6392.73);
insert into holiday (id, country, city, price) values (79, 'China', 'Zuobude', 6365.26);
insert into holiday (id, country, city, price) values (80, 'Brazil', 'Muzambinho', 4108.46);
insert into holiday (id, country, city, price) values (81, 'Czech Republic', 'Postřelmov', 1441.17);
insert into holiday (id, country, city, price) values (82, 'Guatemala', 'San Luis Jilotepeque', 1709.08);
insert into holiday (id, country, city, price) values (83, 'New Zealand', 'Taipa', 3627.81);
insert into holiday (id, country, city, price) values (84, 'China', 'Beishan', 2203.96);
insert into holiday (id, country, city, price) values (85, 'Israel', '‘Uzeir', 2273.42);
insert into holiday (id, country, city, price) values (86, 'Russia', 'Pivovarikha', 4568.69);
insert into holiday (id, country, city, price) values (87, 'Haiti', 'Mayisad', 1996.68);
insert into holiday (id, country, city, price) values (88, 'Palestinian Territory', 'Ya‘bad', 4469.35);
insert into holiday (id, country, city, price) values (89, 'Japan', 'Kawagoe', 7280.27);
insert into holiday (id, country, city, price) values (90, 'China', 'Changshan', 6257.42);
insert into holiday (id, country, city, price) values (91, 'Brazil', 'Curitiba', 7743.19);
insert into holiday (id, country, city, price) values (92, 'China', 'Yangdu', 8609.93);
insert into holiday (id, country, city, price) values (93, 'China', 'Xijiao', 854.69);
insert into holiday (id, country, city, price) values (94, 'Iran', 'Kāshān', 3577.07);
insert into holiday (id, country, city, price) values (95, 'Russia', 'Tolstoy-Yurt', 5481.41);
insert into holiday (id, country, city, price) values (96, 'China', 'Baiba', 1003.64);
insert into holiday (id, country, city, price) values (97, 'China', 'Huangjiazhai', 9309.66);
insert into holiday (id, country, city, price) values (98, 'Latvia', 'Sala', 633.43);
insert into holiday (id, country, city, price) values (99, 'Philippines', 'Baguio', 8889.77);
insert into holiday (id, country, city, price) values (100, 'Croatia', 'Mačkovec', 4540.14);
insert into holiday (id, country, city, price) values (101, 'Cape Verde', 'Tarrafal de São Nicolau', 5290.05);
insert into holiday (id, country, city, price) values (102, 'China', 'Gaoqiao', 6515.61);
insert into holiday (id, country, city, price) values (103, 'Indonesia', 'Sendangkemulian', 2936.5);
insert into holiday (id, country, city, price) values (104, 'Russia', 'Vereya', 2583.01);
insert into holiday (id, country, city, price) values (105, 'Russia', 'Bogoroditsk', 5878.17);
insert into holiday (id, country, city, price) values (106, 'Russia', 'Roslavl’', 8650.48);
insert into holiday (id, country, city, price) values (107, 'Norway', 'Bergen', 8049.67);
insert into holiday (id, country, city, price) values (108, 'China', 'Hubei', 7283.5);
insert into holiday (id, country, city, price) values (109, 'Indonesia', 'Winong', 6862.39);
insert into holiday (id, country, city, price) values (110, 'Philippines', 'Dumalneg', 480.73);
insert into holiday (id, country, city, price) values (111, 'Malaysia', 'Kuching', 1987.16);
insert into holiday (id, country, city, price) values (112, 'Brazil', 'Perdões', 2441.63);
insert into holiday (id, country, city, price) values (113, 'Mexico', 'Miguel Hidalgo', 9011.73);
insert into holiday (id, country, city, price) values (114, 'Myanmar', 'Maubin', 5468.18);
insert into holiday (id, country, city, price) values (115, 'China', 'Xiqi', 6302.86);
insert into holiday (id, country, city, price) values (116, 'Venezuela', 'Tía Juana', 2533.88);
insert into holiday (id, country, city, price) values (117, 'Tunisia', 'Kairouan', 1643.86);
insert into holiday (id, country, city, price) values (118, 'Poland', 'Grabica', 411.34);
insert into holiday (id, country, city, price) values (119, 'China', 'Zhencheng', 8484.82);
insert into holiday (id, country, city, price) values (120, 'Portugal', 'Calvaria de Baixo', 9350.07);
insert into holiday (id, country, city, price) values (121, 'Portugal', 'Olho Marinho', 6351.7);
insert into holiday (id, country, city, price) values (122, 'Russia', 'Chagoda', 102.34);
insert into holiday (id, country, city, price) values (123, 'France', 'Nice', 7047.91);
insert into holiday (id, country, city, price) values (124, 'China', 'Dongping', 7318.69);
insert into holiday (id, country, city, price) values (125, 'China', 'Guandi', 3850.23);
insert into holiday (id, country, city, price) values (126, 'Morocco', 'Zerkten', 3804.18);
insert into holiday (id, country, city, price) values (127, 'Indonesia', 'Arjawinangun', 5219.2);
insert into holiday (id, country, city, price) values (128, 'Greece', 'Néos Oropós', 7231.15);
insert into holiday (id, country, city, price) values (129, 'China', 'Xiadu', 5371.44);
insert into holiday (id, country, city, price) values (130, 'Czech Republic', 'Loštice', 6528.37);
insert into holiday (id, country, city, price) values (131, 'Mauritius', 'Camp Diable', 7762.41);
insert into holiday (id, country, city, price) values (132, 'Philippines', 'Dulangan', 2725.49);
insert into holiday (id, country, city, price) values (133, 'Mexico', 'Guadalupe', 289.17);
insert into holiday (id, country, city, price) values (134, 'Philippines', 'San Isidro', 3278.7);
insert into holiday (id, country, city, price) values (135, 'Uganda', 'Kyankwanzi', 3833.84);
insert into holiday (id, country, city, price) values (136, 'Georgia', 'Tsalka', 7003.43);
insert into holiday (id, country, city, price) values (137, 'Indonesia', 'Sidomulyo Kulon', 1973.98);
insert into holiday (id, country, city, price) values (138, 'Ukraine', 'Volodymyr-Volyns’kyy', 7828.27);
insert into holiday (id, country, city, price) values (139, 'Indonesia', 'Bintang', 9613.05);
insert into holiday (id, country, city, price) values (140, 'Ukraine', 'Rubizhne', 2155.48);
insert into holiday (id, country, city, price) values (141, 'Afghanistan', 'Mandōl', 9694.38);
insert into holiday (id, country, city, price) values (142, 'United States', 'Toledo', 342.27);
insert into holiday (id, country, city, price) values (143, 'Russia', 'Lesogorsk', 3350.1);
insert into holiday (id, country, city, price) values (144, 'Turkmenistan', 'Gowurdak', 4648.13);
insert into holiday (id, country, city, price) values (145, 'Bolivia', 'Mapiri', 1813.63);
insert into holiday (id, country, city, price) values (146, 'United States', 'Battle Creek', 3086.34);
insert into holiday (id, country, city, price) values (147, 'Vietnam', 'Quán Hành', 521.47);
insert into holiday (id, country, city, price) values (148, 'Serbia', 'Debeljača', 267.94);
insert into holiday (id, country, city, price) values (149, 'Finland', 'Punkaharju', 2912.71);
insert into holiday (id, country, city, price) values (150, 'Peru', 'Pallanchacra', 1839.96);
insert into holiday (id, country, city, price) values (151, 'Greece', 'Grevená', 2022.73);
insert into holiday (id, country, city, price) values (152, 'Peru', 'Chillia', 9885.74);
insert into holiday (id, country, city, price) values (153, 'Argentina', 'Gobernador Gálvez', 7713.08);
insert into holiday (id, country, city, price) values (154, 'Poland', 'Mysiadło', 6007.36);
insert into holiday (id, country, city, price) values (155, 'Syria', 'Muḩambal', 3648.17);
insert into holiday (id, country, city, price) values (156, 'Egypt', 'Ţahţā', 8061.25);
insert into holiday (id, country, city, price) values (157, 'China', 'Xingren', 3041.44);
insert into holiday (id, country, city, price) values (158, 'China', 'Lucheng', 111.42);
insert into holiday (id, country, city, price) values (159, 'Palestinian Territory', 'Naḩḩālīn', 4174.94);
insert into holiday (id, country, city, price) values (160, 'Argentina', 'Villa Ángela', 3752.96);
insert into holiday (id, country, city, price) values (161, 'China', 'Nanhai', 6658.46);
insert into holiday (id, country, city, price) values (162, 'United States', 'Fort Worth', 6857.52);
insert into holiday (id, country, city, price) values (163, 'Poland', 'Trzebinia', 7384.92);
insert into holiday (id, country, city, price) values (164, 'Afghanistan', 'Injīl', 3847.64);
insert into holiday (id, country, city, price) values (165, 'China', 'Jiudu', 4831.28);
insert into holiday (id, country, city, price) values (166, 'Indonesia', 'Jangkungkusumo', 5528.21);
insert into holiday (id, country, city, price) values (167, 'Libya', 'Al Abyār', 3971.75);
insert into holiday (id, country, city, price) values (168, 'China', 'Foluo', 7602.3);
insert into holiday (id, country, city, price) values (169, 'Sweden', 'Sandviken', 2034.86);
insert into holiday (id, country, city, price) values (170, 'China', 'Dalubian', 3567.57);
insert into holiday (id, country, city, price) values (171, 'Guatemala', 'San José', 9258.86);
insert into holiday (id, country, city, price) values (172, 'Oman', 'Şaḩam', 2760.77);
insert into holiday (id, country, city, price) values (173, 'China', 'Shilong', 935.83);
insert into holiday (id, country, city, price) values (174, 'China', 'Wujian', 5190.3);
insert into holiday (id, country, city, price) values (175, 'Bulgaria', 'Bratsigovo', 3283.03);
insert into holiday (id, country, city, price) values (176, 'Indonesia', 'Birowo', 345.13);
insert into holiday (id, country, city, price) values (177, 'Bhutan', 'Tsirang', 8181.64);
insert into holiday (id, country, city, price) values (178, 'Philippines', 'Paulba', 1307.86);
insert into holiday (id, country, city, price) values (179, 'Honduras', 'Goascorán', 2536.37);
insert into holiday (id, country, city, price) values (180, 'Sweden', 'Ingarö', 8817.84);
insert into holiday (id, country, city, price) values (181, 'Croatia', 'Špišić-Bukovica', 4123.93);
insert into holiday (id, country, city, price) values (182, 'China', 'Liutao', 9010.46);
insert into holiday (id, country, city, price) values (183, 'Indonesia', 'Sudikampir', 1918.8);
insert into holiday (id, country, city, price) values (184, 'China', 'Xiashihao', 1647.29);
insert into holiday (id, country, city, price) values (185, 'Vietnam', 'Chợ Mới', 533.54);
insert into holiday (id, country, city, price) values (186, 'Greece', 'Pýli', 539.97);
insert into holiday (id, country, city, price) values (187, 'Indonesia', 'Tanjungpecinan Utara', 9452.32);
insert into holiday (id, country, city, price) values (188, 'Brazil', 'Iporã', 6678.77);
insert into holiday (id, country, city, price) values (189, 'Netherlands', 'Rijswijk', 3264.54);
insert into holiday (id, country, city, price) values (190, 'Ethiopia', 'Mojo', 4848.24);
insert into holiday (id, country, city, price) values (191, 'Russia', 'Shalakusha', 1487.64);
insert into holiday (id, country, city, price) values (192, 'Ecuador', 'Cayambe', 6389.95);
insert into holiday (id, country, city, price) values (193, 'Uruguay', 'Florencio Sánchez', 3100.94);
insert into holiday (id, country, city, price) values (194, 'Kazakhstan', 'Taldyqorghan', 5111.48);
insert into holiday (id, country, city, price) values (195, 'China', 'Fenglin', 5716.95);
insert into holiday (id, country, city, price) values (196, 'China', 'Canghou', 346.89);
insert into holiday (id, country, city, price) values (197, 'Uganda', 'Kyegegwa', 272.53);
insert into holiday (id, country, city, price) values (198, 'China', 'Liushan', 4462.66);
insert into holiday (id, country, city, price) values (199, 'Sweden', 'Stockholm', 7850.62);
insert into holiday (id, country, city, price) values (200, 'Czech Republic', 'Bohutín', 9567.63);
insert into holiday (id, country, city, price) values (201, 'France', 'Toulouse', 2269.1);
insert into holiday (id, country, city, price) values (202, 'Portugal', 'Oliveira de Frades', 4234.34);
insert into holiday (id, country, city, price) values (203, 'Mexico', 'Francisco J Mujica', 5246.4);
insert into holiday (id, country, city, price) values (204, 'Yemen', 'Markaz Bilād aţ Ţa‘ām', 4850.77);
insert into holiday (id, country, city, price) values (205, 'Peru', 'Quivilla', 3957.7);
insert into holiday (id, country, city, price) values (206, 'Cuba', 'Nuevitas', 5707.83);
insert into holiday (id, country, city, price) values (207, 'Cuba', 'Sagua de Tánamo', 9463.12);
insert into holiday (id, country, city, price) values (208, 'Poland', 'Waśniów', 9218.58);
insert into holiday (id, country, city, price) values (209, 'Papua New Guinea', 'Kerema', 7428.47);
insert into holiday (id, country, city, price) values (210, 'Slovenia', 'Slovenj Gradec', 328.53);
insert into holiday (id, country, city, price) values (211, 'Albania', 'Derjan', 5742.74);
insert into holiday (id, country, city, price) values (212, 'Belarus', 'Slutsk', 7335.78);
insert into holiday (id, country, city, price) values (213, 'China', 'Zhenqian', 9824.32);
insert into holiday (id, country, city, price) values (214, 'South Africa', 'Bultfontein', 7784.65);
insert into holiday (id, country, city, price) values (215, 'Vietnam', 'Cầu Giấy', 6531.73);
insert into holiday (id, country, city, price) values (216, 'Philippines', 'Caracal', 2468.76);
insert into holiday (id, country, city, price) values (217, 'Poland', 'Biały Bór', 1482.42);
insert into holiday (id, country, city, price) values (218, 'Vietnam', 'Hà Đông', 4871.24);
insert into holiday (id, country, city, price) values (219, 'Argentina', 'El Colorado', 3612.79);
insert into holiday (id, country, city, price) values (220, 'United States', 'Lawrenceville', 3284.11);
insert into holiday (id, country, city, price) values (221, 'Russia', 'Zheleznogorsk', 8924.31);
insert into holiday (id, country, city, price) values (222, 'Netherlands', 'Leeuwarden', 7825.45);
insert into holiday (id, country, city, price) values (223, 'China', 'Shuidun', 3234.0);
insert into holiday (id, country, city, price) values (224, 'Indonesia', 'Banjar Dukuh', 3127.64);
insert into holiday (id, country, city, price) values (225, 'Mexico', 'Buenos Aires', 2638.17);
insert into holiday (id, country, city, price) values (226, 'Indonesia', 'Gesikan', 2153.97);
insert into holiday (id, country, city, price) values (227, 'North Korea', 'Ŭiju', 8550.47);
insert into holiday (id, country, city, price) values (228, 'Greece', 'Ágios Matthaíos', 9961.41);
insert into holiday (id, country, city, price) values (229, 'South Korea', 'Beolgyo', 1324.57);
insert into holiday (id, country, city, price) values (230, 'Russia', 'Taldom', 8326.51);
insert into holiday (id, country, city, price) values (231, 'Egypt', 'Az Zarqā', 2067.59);
insert into holiday (id, country, city, price) values (232, 'Czech Republic', 'Kájov', 4048.4);
insert into holiday (id, country, city, price) values (233, 'China', 'Xishui', 8841.53);
insert into holiday (id, country, city, price) values (234, 'Indonesia', 'Daleman', 5574.67);
insert into holiday (id, country, city, price) values (235, 'Argentina', 'San Pedro', 9254.39);
insert into holiday (id, country, city, price) values (236, 'Japan', 'Hirado', 7028.6);
insert into holiday (id, country, city, price) values (237, 'China', 'Geshan', 3990.8);
insert into holiday (id, country, city, price) values (238, 'Palestinian Territory', 'Şānūr', 2825.17);
insert into holiday (id, country, city, price) values (239, 'Indonesia', 'Lanci Satu', 5492.68);
insert into holiday (id, country, city, price) values (240, 'Cameroon', 'Dschang', 2644.5);
insert into holiday (id, country, city, price) values (241, 'China', 'Bukui', 7751.45);
insert into holiday (id, country, city, price) values (242, 'Albania', 'Pishaj', 2898.32);
insert into holiday (id, country, city, price) values (243, 'China', 'Laoxialu', 1676.92);
insert into holiday (id, country, city, price) values (244, 'Sri Lanka', 'Horana South', 6974.07);
insert into holiday (id, country, city, price) values (245, 'China', 'Lefengzhen', 5373.12);
insert into holiday (id, country, city, price) values (246, 'China', 'Miao’ergou', 2583.76);
insert into holiday (id, country, city, price) values (247, 'Brazil', 'Caruaru', 3989.01);
insert into holiday (id, country, city, price) values (248, 'United States', 'Albuquerque', 6086.95);
insert into holiday (id, country, city, price) values (249, 'Greece', 'Papágou', 9450.52);
insert into holiday (id, country, city, price) values (250, 'Russia', 'Liski', 3665.58);
insert into holiday (id, country, city, price) values (251, 'Morocco', 'Tabant', 4631.06);
insert into holiday (id, country, city, price) values (252, 'China', 'Zhayang', 313.73);
insert into holiday (id, country, city, price) values (253, 'China', 'Dahedian', 6458.88);
insert into holiday (id, country, city, price) values (254, 'France', 'Paris 16', 1147.78);
insert into holiday (id, country, city, price) values (255, 'China', 'Nawu', 8452.16);
insert into holiday (id, country, city, price) values (256, 'United States', 'Detroit', 1095.32);
insert into holiday (id, country, city, price) values (257, 'Russia', 'Nesterov', 3498.41);
insert into holiday (id, country, city, price) values (258, 'Czech Republic', 'Hudlice', 3032.59);
insert into holiday (id, country, city, price) values (259, 'Costa Rica', 'San Isidro', 5788.69);
insert into holiday (id, country, city, price) values (260, 'Albania', 'Lezhë', 8513.48);
insert into holiday (id, country, city, price) values (261, 'Indonesia', 'Prigi', 798.92);
insert into holiday (id, country, city, price) values (262, 'Serbia', 'Jevremovac', 166.57);
insert into holiday (id, country, city, price) values (263, 'Thailand', 'Nakhon Si Thammarat', 5022.93);
insert into holiday (id, country, city, price) values (264, 'Palestinian Territory', 'Dayr Sharaf', 8128.52);
insert into holiday (id, country, city, price) values (265, 'Italy', 'Villanova', 8257.45);
insert into holiday (id, country, city, price) values (266, 'Slovenia', 'Radlje ob Dravi', 6959.24);
insert into holiday (id, country, city, price) values (267, 'Spain', 'Sant Cugat Del Valles', 3863.31);
insert into holiday (id, country, city, price) values (268, 'Russia', 'Leninskiy', 7393.08);
insert into holiday (id, country, city, price) values (269, 'Russia', 'Lesogorsk', 3604.74);
insert into holiday (id, country, city, price) values (270, 'Japan', 'Yashiro', 7780.69);
insert into holiday (id, country, city, price) values (271, 'Argentina', 'General Conesa', 3136.04);
insert into holiday (id, country, city, price) values (272, 'Yemen', 'Ḩabbān', 1271.16);
insert into holiday (id, country, city, price) values (273, 'Ukraine', 'Chornyanka', 9319.47);
insert into holiday (id, country, city, price) values (274, 'France', 'Niort', 1387.76);
insert into holiday (id, country, city, price) values (275, 'New Caledonia', 'Koumac', 3387.72);
insert into holiday (id, country, city, price) values (276, 'Ecuador', 'Guayaquil', 1945.62);
insert into holiday (id, country, city, price) values (277, 'Portugal', 'Lordelo', 4138.6);
insert into holiday (id, country, city, price) values (278, 'China', 'Fanrong', 1463.02);
insert into holiday (id, country, city, price) values (279, 'Indonesia', 'Dadapan', 5960.47);
insert into holiday (id, country, city, price) values (280, 'Kenya', 'Embu', 6220.95);
insert into holiday (id, country, city, price) values (281, 'Russia', 'Zavoronezhskoye', 5029.39);
insert into holiday (id, country, city, price) values (282, 'Argentina', 'Los Frentones', 3929.16);
insert into holiday (id, country, city, price) values (283, 'China', 'Pingshui', 7557.63);
insert into holiday (id, country, city, price) values (284, 'Honduras', 'Potrerillos', 5135.44);
insert into holiday (id, country, city, price) values (285, 'Russia', 'Palana', 6988.36);
insert into holiday (id, country, city, price) values (286, 'China', 'Luoshan', 1557.96);
insert into holiday (id, country, city, price) values (287, 'Russia', 'Polevskoy', 8473.47);
insert into holiday (id, country, city, price) values (288, 'Kenya', 'Rongai', 2099.63);
insert into holiday (id, country, city, price) values (289, 'Palestinian Territory', 'Kafr Qūd', 530.51);
insert into holiday (id, country, city, price) values (290, 'Gambia', 'Farafenni', 1864.56);
insert into holiday (id, country, city, price) values (291, 'Germany', 'Remscheid', 100.64);
insert into holiday (id, country, city, price) values (292, 'Tunisia', 'Al Mazzūnah', 7570.76);
insert into holiday (id, country, city, price) values (293, 'Canada', 'Devon', 808.78);
insert into holiday (id, country, city, price) values (294, 'China', 'Yengimahalla', 6157.86);
insert into holiday (id, country, city, price) values (295, 'Canada', 'Killam', 2953.31);
insert into holiday (id, country, city, price) values (296, 'United States', 'Washington', 3881.59);
insert into holiday (id, country, city, price) values (297, 'Czech Republic', 'Větřní', 3065.46);
insert into holiday (id, country, city, price) values (298, 'Indonesia', 'Kendung Timur', 3394.89);
insert into holiday (id, country, city, price) values (299, 'North Korea', 'Hŭngju-dong', 5986.77);
insert into holiday (id, country, city, price) values (300, 'China', 'Pingshan', 2538.84);
insert into holiday (id, country, city, price) values (301, 'Malaysia', 'Sandakan', 7299.3);
insert into holiday (id, country, city, price) values (302, 'Syria', 'Ḩammām Wāşil', 4689.35);
insert into holiday (id, country, city, price) values (303, 'Albania', 'Kushovë', 5816.34);
insert into holiday (id, country, city, price) values (304, 'Greece', 'Chrysoúpolis', 430.42);
insert into holiday (id, country, city, price) values (305, 'Netherlands', 'Middelburg', 1750.05);
insert into holiday (id, country, city, price) values (306, 'China', 'Linshui', 5873.31);
insert into holiday (id, country, city, price) values (307, 'Indonesia', 'Talagasari', 1773.03);
insert into holiday (id, country, city, price) values (308, 'Poland', 'Konstancin-Jeziorna', 6078.24);
insert into holiday (id, country, city, price) values (309, 'Iran', 'Lordegān', 5055.47);
insert into holiday (id, country, city, price) values (310, 'China', 'Sijiqing', 4235.82);
insert into holiday (id, country, city, price) values (311, 'Philippines', 'Alegria', 5827.95);
insert into holiday (id, country, city, price) values (312, 'Brazil', 'Lago da Pedra', 9221.47);
insert into holiday (id, country, city, price) values (313, 'China', 'Lengshuitan', 2513.85);
insert into holiday (id, country, city, price) values (314, 'France', 'Marseille', 2533.69);
insert into holiday (id, country, city, price) values (315, 'France', 'Saint-Brieuc', 4354.08);
insert into holiday (id, country, city, price) values (316, 'Solomon Islands', 'Honiara', 3670.56);
insert into holiday (id, country, city, price) values (317, 'China', 'Bailai', 6960.5);
insert into holiday (id, country, city, price) values (318, 'Nicaragua', 'Masaya', 8387.51);
insert into holiday (id, country, city, price) values (319, 'Philippines', 'Santa Praxedes', 2698.6);
insert into holiday (id, country, city, price) values (320, 'Philippines', 'Taloy', 836.22);
insert into holiday (id, country, city, price) values (321, 'Serbia', 'Pirot', 4766.54);
insert into holiday (id, country, city, price) values (322, 'South Africa', 'Himeville', 2951.27);
insert into holiday (id, country, city, price) values (323, 'China', 'Dongchong', 761.08);
insert into holiday (id, country, city, price) values (324, 'United Kingdom', 'Upton', 9108.82);
insert into holiday (id, country, city, price) values (325, 'Brazil', 'Medina', 9047.01);
insert into holiday (id, country, city, price) values (326, 'Pakistan', 'Nasīrābād', 1147.43);
insert into holiday (id, country, city, price) values (327, 'Malaysia', 'Kota Kinabalu', 4812.48);
insert into holiday (id, country, city, price) values (328, 'Indonesia', 'Gugut', 2328.44);
insert into holiday (id, country, city, price) values (329, 'China', 'Yangjiao', 9828.86);
insert into holiday (id, country, city, price) values (330, 'Poland', 'Kobylanka', 7931.35);
insert into holiday (id, country, city, price) values (331, 'Portugal', 'Figueira Castelo Rodrigo', 9891.11);
insert into holiday (id, country, city, price) values (332, 'Philippines', 'Lusacan', 3119.64);
insert into holiday (id, country, city, price) values (333, 'France', 'Melun', 8530.14);
insert into holiday (id, country, city, price) values (334, 'China', 'Guancheng', 6734.95);
insert into holiday (id, country, city, price) values (335, 'Brazil', 'São Sebastião do Passé', 1420.46);
insert into holiday (id, country, city, price) values (336, 'Indonesia', 'Gunungjulang', 3493.51);
insert into holiday (id, country, city, price) values (337, 'Finland', 'Valtimo', 742.03);
insert into holiday (id, country, city, price) values (338, 'Indonesia', 'Margabakti', 6607.64);
insert into holiday (id, country, city, price) values (339, 'China', 'Tianjiaba', 5369.93);
insert into holiday (id, country, city, price) values (340, 'Israel', 'Jerusalem', 7649.17);
insert into holiday (id, country, city, price) values (341, 'Greece', 'Áyios Nikólaos', 6985.37);
insert into holiday (id, country, city, price) values (342, 'Canada', 'Moose Jaw', 1766.2);
insert into holiday (id, country, city, price) values (343, 'China', 'Xekar', 2545.57);
insert into holiday (id, country, city, price) values (344, 'Poland', 'Miastko', 7727.53);
insert into holiday (id, country, city, price) values (345, 'Serbia', 'Ljukovo', 6661.8);
insert into holiday (id, country, city, price) values (346, 'China', 'Changjiang', 6618.58);
insert into holiday (id, country, city, price) values (347, 'Argentina', 'San Javier', 8091.77);
insert into holiday (id, country, city, price) values (348, 'Indonesia', 'Pinrang', 3894.01);
insert into holiday (id, country, city, price) values (349, 'Indonesia', 'Tangkanpulit', 7518.17);
insert into holiday (id, country, city, price) values (350, 'Philippines', 'Bombon', 8338.36);
insert into holiday (id, country, city, price) values (351, 'Niger', 'Zinder', 5871.54);
insert into holiday (id, country, city, price) values (352, 'China', 'Wutan', 5713.02);
insert into holiday (id, country, city, price) values (353, 'Portugal', 'Casa Nova', 2992.16);
insert into holiday (id, country, city, price) values (354, 'Sweden', 'Kinna', 7967.61);
insert into holiday (id, country, city, price) values (355, 'Kenya', 'Machakos', 1750.36);
insert into holiday (id, country, city, price) values (356, 'Saint Vincent and the Grenadines', 'Port Elizabeth', 2984.43);
insert into holiday (id, country, city, price) values (357, 'Jordan', 'Karak City', 7452.06);
insert into holiday (id, country, city, price) values (358, 'Argentina', 'Famaillá', 2071.13);
insert into holiday (id, country, city, price) values (359, 'China', 'Yangdian', 5972.94);
insert into holiday (id, country, city, price) values (360, 'Brazil', 'Sacramento', 5178.92);
insert into holiday (id, country, city, price) values (361, 'Somalia', 'Ceelbuur', 3173.31);
insert into holiday (id, country, city, price) values (362, 'Finland', 'Teuva', 1582.97);
insert into holiday (id, country, city, price) values (363, 'Japan', 'Nishi-Tokyo-shi', 6455.01);
insert into holiday (id, country, city, price) values (364, 'Brazil', 'Caeté', 680.19);
insert into holiday (id, country, city, price) values (365, 'Haiti', 'Chambellan', 1589.28);
insert into holiday (id, country, city, price) values (366, 'Poland', 'Wyszogród', 8452.27);
insert into holiday (id, country, city, price) values (367, 'Ivory Coast', 'Soubré', 7727.39);
insert into holiday (id, country, city, price) values (368, 'Japan', 'Kushikino', 3067.04);
insert into holiday (id, country, city, price) values (369, 'Ukraine', 'Vyzhnytsya', 5775.06);
insert into holiday (id, country, city, price) values (370, 'China', 'Huaxijie', 7172.46);
insert into holiday (id, country, city, price) values (371, 'Greece', 'Kalávryta', 9353.44);
insert into holiday (id, country, city, price) values (372, 'China', 'Guajiasi', 5075.28);
insert into holiday (id, country, city, price) values (373, 'Portugal', 'Casal', 2979.29);
insert into holiday (id, country, city, price) values (374, 'Palestinian Territory', 'Bazzāryah', 940.43);
insert into holiday (id, country, city, price) values (375, 'Mexico', 'Morelos', 9741.01);
insert into holiday (id, country, city, price) values (376, 'China', 'Yangpu', 3456.13);
insert into holiday (id, country, city, price) values (377, 'Japan', 'Nōgata', 6479.9);
insert into holiday (id, country, city, price) values (378, 'Lithuania', 'Ukmerge', 8913.87);
insert into holiday (id, country, city, price) values (379, 'Spain', 'Zaragoza', 2292.32);
insert into holiday (id, country, city, price) values (380, 'Iran', 'Tehrān', 2013.93);
insert into holiday (id, country, city, price) values (381, 'Russia', 'Rudnya', 9898.55);
insert into holiday (id, country, city, price) values (382, 'France', 'Paris 15', 3483.4);
insert into holiday (id, country, city, price) values (383, 'Poland', 'Pogwizdów', 200.94);
insert into holiday (id, country, city, price) values (384, 'Russia', 'Tsivil’sk', 4061.21);
insert into holiday (id, country, city, price) values (385, 'Spain', 'Vitoria-Gasteiz', 4499.51);
insert into holiday (id, country, city, price) values (386, 'Pakistan', 'Khurriānwāla', 1754.76);
insert into holiday (id, country, city, price) values (387, 'Moldova', 'Maiac', 6088.88);
insert into holiday (id, country, city, price) values (388, 'Russia', 'Krasnyy Klyuch', 335.53);
insert into holiday (id, country, city, price) values (389, 'Mexico', 'Miguel Hidalgo', 3166.65);
insert into holiday (id, country, city, price) values (390, 'Portugal', 'Sande São Martinho', 6963.84);
insert into holiday (id, country, city, price) values (391, 'Indonesia', 'Samburat', 411.17);
insert into holiday (id, country, city, price) values (392, 'China', 'Zeguo', 1007.6);
insert into holiday (id, country, city, price) values (393, 'China', 'Kanshi', 3247.88);
insert into holiday (id, country, city, price) values (394, 'China', 'Huangzhuang', 2406.41);
insert into holiday (id, country, city, price) values (395, 'Thailand', 'Chang Klang', 5809.39);
insert into holiday (id, country, city, price) values (396, 'Tajikistan', 'Khovaling', 3742.11);
insert into holiday (id, country, city, price) values (397, 'Venezuela', 'Cabimas', 6154.67);
insert into holiday (id, country, city, price) values (398, 'Portugal', 'Alburitel', 204.08);
insert into holiday (id, country, city, price) values (399, 'China', 'Zhouyuan', 7834.24);
insert into holiday (id, country, city, price) values (400, 'United Kingdom', 'London', 1798.86);
insert into holiday (id, country, city, price) values (401, 'Colombia', 'Madrid', 3920.69);
insert into holiday (id, country, city, price) values (402, 'Japan', 'Kurashiki', 6194.25);
insert into holiday (id, country, city, price) values (403, 'Philippines', 'Dacudao', 1770.87);
insert into holiday (id, country, city, price) values (404, 'Mexico', 'Obrera', 5906.7);
insert into holiday (id, country, city, price) values (405, 'Brazil', 'São Caetano do Sul', 633.67);
insert into holiday (id, country, city, price) values (406, 'Greece', 'Firá', 5653.28);
insert into holiday (id, country, city, price) values (407, 'China', 'Tianhe', 3550.15);
insert into holiday (id, country, city, price) values (408, 'Indonesia', 'Klampis', 9542.82);
insert into holiday (id, country, city, price) values (409, 'Democratic Republic of the Congo', 'Bandundu', 8467.4);
insert into holiday (id, country, city, price) values (410, 'Russia', 'Kachkanar', 1487.61);
insert into holiday (id, country, city, price) values (411, 'Canada', 'Nanton', 8138.65);
insert into holiday (id, country, city, price) values (412, 'Poland', 'Koszęcin', 6403.8);
insert into holiday (id, country, city, price) values (413, 'Indonesia', 'Citeureup', 940.06);
insert into holiday (id, country, city, price) values (414, 'Brazil', 'Ipojuca', 4307.58);
insert into holiday (id, country, city, price) values (415, 'China', 'Qiankou', 924.16);
insert into holiday (id, country, city, price) values (416, 'Poland', 'Osiek nad Notecią', 4974.95);
insert into holiday (id, country, city, price) values (417, 'Poland', 'Osieczany', 7953.77);
insert into holiday (id, country, city, price) values (418, 'Togo', 'Bassar', 2337.67);
insert into holiday (id, country, city, price) values (419, 'New Zealand', 'Coromandel', 8520.55);
insert into holiday (id, country, city, price) values (420, 'Indonesia', 'Cilentung', 2390.29);
insert into holiday (id, country, city, price) values (421, 'Colombia', 'Pijao', 4094.2);
insert into holiday (id, country, city, price) values (422, 'Indonesia', 'Panenggoede', 6639.95);
insert into holiday (id, country, city, price) values (423, 'France', 'Limoges', 6839.27);
insert into holiday (id, country, city, price) values (424, 'Poland', 'Buk', 2961.99);
insert into holiday (id, country, city, price) values (425, 'Russia', 'Vyborg', 2304.68);
insert into holiday (id, country, city, price) values (426, 'Mexico', 'Los Pinos', 2059.61);
insert into holiday (id, country, city, price) values (427, 'China', 'Gongqiao', 214.4);
insert into holiday (id, country, city, price) values (428, 'Czech Republic', 'Hrabyně', 4854.97);
insert into holiday (id, country, city, price) values (429, 'China', 'Cangyou', 1242.55);
insert into holiday (id, country, city, price) values (430, 'South Sudan', 'Yambio', 3923.32);
insert into holiday (id, country, city, price) values (431, 'Russia', 'Yug', 2263.41);
insert into holiday (id, country, city, price) values (432, 'Norway', 'Trondheim', 6583.34);
insert into holiday (id, country, city, price) values (433, 'United States', 'Grand Rapids', 6260.62);
insert into holiday (id, country, city, price) values (434, 'Albania', 'Karinë', 5189.79);
insert into holiday (id, country, city, price) values (435, 'Portugal', 'Ferreiros', 9335.24);
insert into holiday (id, country, city, price) values (436, 'Indonesia', 'Gerong', 3789.3);
insert into holiday (id, country, city, price) values (437, 'Poland', 'Praszka', 4215.63);
insert into holiday (id, country, city, price) values (438, 'Philippines', 'Loreto', 7153.03);
insert into holiday (id, country, city, price) values (439, 'China', 'Yingkeng', 2827.38);
insert into holiday (id, country, city, price) values (440, 'China', 'Chashan', 9604.6);
insert into holiday (id, country, city, price) values (441, 'Indonesia', 'Cipatujah', 844.93);
insert into holiday (id, country, city, price) values (442, 'Indonesia', 'Cikiray', 2627.69);
insert into holiday (id, country, city, price) values (443, 'China', 'Xiaochengzi', 6304.37);
insert into holiday (id, country, city, price) values (444, 'Russia', 'Zhukovskiy', 968.43);
insert into holiday (id, country, city, price) values (445, 'Indonesia', 'Suwatu', 5150.15);
insert into holiday (id, country, city, price) values (446, 'Brazil', 'Itapecuru Mirim', 7181.82);
insert into holiday (id, country, city, price) values (447, 'France', 'Albertville', 504.26);
insert into holiday (id, country, city, price) values (448, 'Japan', 'Shizukuishi', 5582.89);
insert into holiday (id, country, city, price) values (449, 'Norway', 'Oslo', 8616.45);
insert into holiday (id, country, city, price) values (450, 'Sri Lanka', 'Kelaniya', 839.23);
insert into holiday (id, country, city, price) values (451, 'Russia', 'Yakutsk', 8077.39);
insert into holiday (id, country, city, price) values (452, 'Burundi', 'Bujumbura', 9154.69);
insert into holiday (id, country, city, price) values (453, 'France', 'Saint-Gratien', 2869.02);
insert into holiday (id, country, city, price) values (454, 'Indonesia', 'Sarkanjut', 7957.98);
insert into holiday (id, country, city, price) values (455, 'China', 'Gushui', 8064.55);
insert into holiday (id, country, city, price) values (456, 'France', 'Grenoble', 8807.82);
insert into holiday (id, country, city, price) values (457, 'France', 'Reims', 9035.26);
insert into holiday (id, country, city, price) values (458, 'China', 'Youlan', 9523.73);
insert into holiday (id, country, city, price) values (459, 'Japan', 'Mooka', 4976.77);
insert into holiday (id, country, city, price) values (460, 'China', 'Youguzhuang', 2685.38);
insert into holiday (id, country, city, price) values (461, 'China', 'Xia’ertai', 3498.92);
insert into holiday (id, country, city, price) values (462, 'Georgia', 'Gali', 8310.97);
insert into holiday (id, country, city, price) values (463, 'South Africa', 'White River', 9605.76);
insert into holiday (id, country, city, price) values (464, 'Brazil', 'Socorro', 3138.64);
insert into holiday (id, country, city, price) values (465, 'Ethiopia', 'Mojo', 4119.45);
insert into holiday (id, country, city, price) values (466, 'Poland', 'Świecie nad Osą', 7164.63);
insert into holiday (id, country, city, price) values (467, 'Indonesia', 'Mancogeh', 4507.01);
insert into holiday (id, country, city, price) values (468, 'Russia', 'Krasnoarmeysk', 2846.49);
insert into holiday (id, country, city, price) values (469, 'Gabon', 'Ntoum', 7835.41);
insert into holiday (id, country, city, price) values (470, 'Indonesia', 'Bandungsari', 4068.33);
insert into holiday (id, country, city, price) values (471, 'Cyprus', 'Émpa', 7548.76);
insert into holiday (id, country, city, price) values (472, 'United States', 'Denver', 8439.94);
insert into holiday (id, country, city, price) values (473, 'Iran', 'Qeshm', 9729.14);
insert into holiday (id, country, city, price) values (474, 'Latvia', 'Jēkabpils', 9405.97);
insert into holiday (id, country, city, price) values (475, 'Portugal', 'Terra Chã', 9870.54);
insert into holiday (id, country, city, price) values (476, 'Indonesia', 'Juranalas', 6495.1);
insert into holiday (id, country, city, price) values (477, 'Philippines', 'Anambongan', 7304.25);
insert into holiday (id, country, city, price) values (478, 'Croatia', 'Višnjevac', 5274.37);
insert into holiday (id, country, city, price) values (479, 'North Korea', 'Samho-rodongjagu', 2314.98);
insert into holiday (id, country, city, price) values (480, 'Poland', 'Wydminy', 1839.7);
insert into holiday (id, country, city, price) values (481, 'Netherlands', 'Schiedam postbusnummers', 2959.03);
insert into holiday (id, country, city, price) values (482, 'China', 'Changlu', 9517.24);
insert into holiday (id, country, city, price) values (483, 'Philippines', 'Manga', 7775.54);
insert into holiday (id, country, city, price) values (484, 'Indonesia', 'Sedati', 9317.76);
insert into holiday (id, country, city, price) values (485, 'Indonesia', 'Tembeling', 2451.46);
insert into holiday (id, country, city, price) values (486, 'Brazil', 'Ubatã', 8537.91);
insert into holiday (id, country, city, price) values (487, 'Thailand', 'Soi Dao', 2080.24);
insert into holiday (id, country, city, price) values (488, 'Russia', 'Shelabolikha', 3343.8);
insert into holiday (id, country, city, price) values (489, 'Indonesia', 'Awar-awar', 2323.8);
insert into holiday (id, country, city, price) values (490, 'China', 'Kesheng', 2143.3);
insert into holiday (id, country, city, price) values (491, 'Lithuania', 'Kėdainiai', 4307.15);
insert into holiday (id, country, city, price) values (492, 'China', 'Zhongdong', 213.28);
insert into holiday (id, country, city, price) values (493, 'Brazil', 'Vargem Grande do Sul', 9786.86);
insert into holiday (id, country, city, price) values (494, 'China', 'Darya Boyi', 7263.81);
insert into holiday (id, country, city, price) values (495, 'China', 'Zhongxi', 7966.32);
insert into holiday (id, country, city, price) values (496, 'China', 'Daxing', 6089.1);
insert into holiday (id, country, city, price) values (497, 'Indonesia', 'Sukomulyo', 7330.45);
insert into holiday (id, country, city, price) values (498, 'Indonesia', 'Banjar Asahduren', 8810.15);
insert into holiday (id, country, city, price) values (499, 'Portugal', 'Ribeira Seca', 7564.78);
insert into holiday (id, country, city, price) values (500, 'Philippines', 'Cuevas', 5862.89);
insert into holiday (id, country, city, price) values (501, 'Russia', 'Borisova Griva', 1803.3);
insert into holiday (id, country, city, price) values (502, 'Peru', 'Cahuacho', 1222.36);
insert into holiday (id, country, city, price) values (503, 'Jamaica', 'Lluidas Vale', 1670.6);
insert into holiday (id, country, city, price) values (504, 'Oman', 'Bayt al ‘Awābī', 7381.61);
insert into holiday (id, country, city, price) values (505, 'South Africa', 'Camperdown', 1820.56);
insert into holiday (id, country, city, price) values (506, 'Indonesia', 'Jambangan', 2023.5);
insert into holiday (id, country, city, price) values (507, 'China', 'Qiulu', 3742.75);
insert into holiday (id, country, city, price) values (508, 'Philippines', 'Pangian', 8154.3);
insert into holiday (id, country, city, price) values (509, 'South Africa', 'Messina', 6335.31);
insert into holiday (id, country, city, price) values (510, 'Czech Republic', 'Leština', 9711.42);
insert into holiday (id, country, city, price) values (511, 'Portugal', 'Monte', 6691.09);
insert into holiday (id, country, city, price) values (512, 'Germany', 'Leipzig', 9428.78);
insert into holiday (id, country, city, price) values (513, 'China', 'Potou', 2053.25);
insert into holiday (id, country, city, price) values (514, 'Czech Republic', 'Vlachovice', 6194.42);
insert into holiday (id, country, city, price) values (515, 'Honduras', 'Sulaco', 2863.68);
insert into holiday (id, country, city, price) values (516, 'Philippines', 'Cabittaogan', 7131.66);
insert into holiday (id, country, city, price) values (517, 'Lithuania', 'Lazdijai', 9045.35);
insert into holiday (id, country, city, price) values (518, 'China', 'Qingxi', 1648.46);
insert into holiday (id, country, city, price) values (519, 'Malaysia', 'Seremban', 8909.56);
insert into holiday (id, country, city, price) values (520, 'Malaysia', 'Kuala Terengganu', 226.12);
insert into holiday (id, country, city, price) values (521, 'China', 'Yuetang', 3159.82);
insert into holiday (id, country, city, price) values (522, 'Brazil', 'Itápolis', 5214.6);
insert into holiday (id, country, city, price) values (523, 'Madagascar', 'Nosy Varika', 3688.48);
insert into holiday (id, country, city, price) values (524, 'China', 'Wuxiang', 3337.68);
insert into holiday (id, country, city, price) values (525, 'Philippines', 'Estacion', 693.93);
insert into holiday (id, country, city, price) values (526, 'Philippines', 'Maulawin', 3879.93);
insert into holiday (id, country, city, price) values (527, 'Brazil', 'Itiruçu', 2191.29);
insert into holiday (id, country, city, price) values (528, 'Paraguay', 'Tacuatí', 5101.05);
insert into holiday (id, country, city, price) values (529, 'Indonesia', 'Pondokwungu', 8340.46);
insert into holiday (id, country, city, price) values (530, 'Brazil', 'Taquaritinga', 2718.61);
insert into holiday (id, country, city, price) values (531, 'Colombia', 'Cachipay', 7976.15);
insert into holiday (id, country, city, price) values (532, 'Macedonia', 'Неготино', 3966.52);
insert into holiday (id, country, city, price) values (533, 'Philippines', 'Sagud-Bahley', 7908.8);
insert into holiday (id, country, city, price) values (534, 'United States', 'Milwaukee', 5006.38);
insert into holiday (id, country, city, price) values (535, 'Brazil', 'Santa Inês', 3722.83);
insert into holiday (id, country, city, price) values (536, 'Indonesia', 'Krajan', 9990.57);
insert into holiday (id, country, city, price) values (537, 'Brazil', 'Simões Filho', 8323.89);
insert into holiday (id, country, city, price) values (538, 'Canada', 'Saint-Joseph-de-Coleraine', 8439.24);
insert into holiday (id, country, city, price) values (539, 'China', 'Yutan', 8365.7);
insert into holiday (id, country, city, price) values (540, 'Sweden', 'Sundsvall', 7917.97);
insert into holiday (id, country, city, price) values (541, 'Ukraine', 'Rudky', 5625.62);
insert into holiday (id, country, city, price) values (542, 'Slovenia', 'Bovec', 1290.0);
insert into holiday (id, country, city, price) values (543, 'Russia', 'Krasnoye', 2612.62);
insert into holiday (id, country, city, price) values (544, 'Russia', 'Pytalovo', 3676.86);
insert into holiday (id, country, city, price) values (545, 'Indonesia', 'Sambong', 4127.74);
insert into holiday (id, country, city, price) values (546, 'China', 'Huanghua', 2529.05);
insert into holiday (id, country, city, price) values (547, 'Palestinian Territory', 'Jūrat ash Sham‘ah', 4662.86);
insert into holiday (id, country, city, price) values (548, 'Indonesia', 'Nangabulik', 2335.22);
insert into holiday (id, country, city, price) values (549, 'Bulgaria', 'Sadovo', 2649.18);
insert into holiday (id, country, city, price) values (550, 'China', 'Taoyang', 2364.49);
insert into holiday (id, country, city, price) values (551, 'Sierra Leone', 'Magburaka', 1195.16);
insert into holiday (id, country, city, price) values (552, 'Albania', 'Roshnik', 2650.97);
insert into holiday (id, country, city, price) values (553, 'Peru', 'Pucacaca', 8454.46);
insert into holiday (id, country, city, price) values (554, 'Brazil', 'Sidrolândia', 8504.31);
insert into holiday (id, country, city, price) values (555, 'China', 'Dongla', 5914.0);
insert into holiday (id, country, city, price) values (556, 'France', 'Bayonne', 3279.17);
insert into holiday (id, country, city, price) values (557, 'Germany', 'München', 8534.65);
insert into holiday (id, country, city, price) values (558, 'Portugal', 'Chãos', 1601.12);
insert into holiday (id, country, city, price) values (559, 'Guatemala', 'San José', 3618.55);
insert into holiday (id, country, city, price) values (560, 'Colombia', 'Guacarí', 8091.07);
insert into holiday (id, country, city, price) values (561, 'China', 'Gemo', 1902.3);
insert into holiday (id, country, city, price) values (562, 'Croatia', 'Jastrebarsko', 3949.75);
insert into holiday (id, country, city, price) values (563, 'Greece', 'Kolchikón', 1272.73);
insert into holiday (id, country, city, price) values (564, 'Thailand', 'Kaeng Khoi', 3683.56);
insert into holiday (id, country, city, price) values (565, 'Ukraine', 'Krasnoarmiys’k', 2049.71);
insert into holiday (id, country, city, price) values (566, 'Portugal', 'Aveleda', 8792.64);
insert into holiday (id, country, city, price) values (567, 'Poland', 'Kołaczyce', 3089.82);
insert into holiday (id, country, city, price) values (568, 'Mexico', 'San Miguel', 769.16);
insert into holiday (id, country, city, price) values (569, 'Philippines', 'Quilo-quilo', 6929.54);
insert into holiday (id, country, city, price) values (570, 'Philippines', 'Patabog', 371.68);
insert into holiday (id, country, city, price) values (571, 'Brazil', 'Ibitinga', 2846.0);
insert into holiday (id, country, city, price) values (572, 'Argentina', 'Marcos Juárez', 171.89);
insert into holiday (id, country, city, price) values (573, 'China', 'Moba', 6874.21);
insert into holiday (id, country, city, price) values (574, 'Ukraine', 'Kamieniec Podolski', 7321.17);
insert into holiday (id, country, city, price) values (575, 'United States', 'Louisville', 9182.43);
insert into holiday (id, country, city, price) values (576, 'Russia', 'Itatskiy', 4413.11);
insert into holiday (id, country, city, price) values (577, 'Russia', 'Yessentuki', 2466.42);
insert into holiday (id, country, city, price) values (578, 'China', 'Sanzhou', 2004.21);
insert into holiday (id, country, city, price) values (579, 'Indonesia', 'Ciranca', 8032.92);
insert into holiday (id, country, city, price) values (580, 'Vietnam', 'Yên Thành', 9675.87);
insert into holiday (id, country, city, price) values (581, 'Indonesia', 'Kelapa', 3362.19);
insert into holiday (id, country, city, price) values (582, 'China', 'Zhumadian', 4671.71);
insert into holiday (id, country, city, price) values (583, 'Philippines', 'Lemery', 406.24);
insert into holiday (id, country, city, price) values (584, 'Indonesia', 'Randuagung', 1552.84);
insert into holiday (id, country, city, price) values (585, 'Uruguay', 'Migues', 5142.03);
insert into holiday (id, country, city, price) values (586, 'Portugal', 'Martingança-Gare', 4940.51);
insert into holiday (id, country, city, price) values (587, 'Tanzania', 'Hedaru', 8581.46);
insert into holiday (id, country, city, price) values (588, 'Sweden', 'Eksjö', 9018.31);
insert into holiday (id, country, city, price) values (589, 'Indonesia', 'Purworejo', 4744.04);
insert into holiday (id, country, city, price) values (590, 'China', 'Ruchihe', 3382.1);
insert into holiday (id, country, city, price) values (591, 'Indonesia', 'Sukamaju', 4615.02);
insert into holiday (id, country, city, price) values (592, 'Nigeria', 'Kaingiwa', 2559.97);
insert into holiday (id, country, city, price) values (593, 'Russia', 'Ust’-Ilimsk', 9604.7);
insert into holiday (id, country, city, price) values (594, 'Indonesia', 'Semarang', 4443.04);
insert into holiday (id, country, city, price) values (595, 'Croatia', 'Punat', 157.07);
insert into holiday (id, country, city, price) values (596, 'China', 'Qincheng', 2993.47);
insert into holiday (id, country, city, price) values (597, 'Albania', 'Lazarat', 1116.81);
insert into holiday (id, country, city, price) values (598, 'Indonesia', 'Sukacai', 1966.72);
insert into holiday (id, country, city, price) values (599, 'United States', 'Fresno', 1148.68);
insert into holiday (id, country, city, price) values (600, 'China', 'Lanyi', 5562.62);
insert into holiday (id, country, city, price) values (601, 'Brazil', 'Canavieiras', 6567.71);
insert into holiday (id, country, city, price) values (602, 'Egypt', 'Dikirnis', 8777.36);
insert into holiday (id, country, city, price) values (603, 'Poland', 'Osielec', 5012.26);
insert into holiday (id, country, city, price) values (604, 'China', 'Sifangxi', 8007.27);
insert into holiday (id, country, city, price) values (605, 'Montenegro', 'Herceg-Novi', 1853.92);
insert into holiday (id, country, city, price) values (606, 'Indonesia', 'Pakalongan', 7231.99);
insert into holiday (id, country, city, price) values (607, 'Pakistan', 'Malakwāl', 3038.86);
insert into holiday (id, country, city, price) values (608, 'China', 'Dianshui', 5674.32);
insert into holiday (id, country, city, price) values (609, 'Sweden', 'Nässjö', 5298.66);
insert into holiday (id, country, city, price) values (610, 'Philippines', 'Cagdianao', 3727.0);
insert into holiday (id, country, city, price) values (611, 'Finland', 'Urjala', 9045.89);
insert into holiday (id, country, city, price) values (612, 'Serbia', 'Doroslovo', 153.65);
insert into holiday (id, country, city, price) values (613, 'Japan', 'Yao', 342.14);
insert into holiday (id, country, city, price) values (614, 'Sweden', 'Dalsjöfors', 2851.33);
insert into holiday (id, country, city, price) values (615, 'Poland', 'Lelkowo', 4687.23);
insert into holiday (id, country, city, price) values (616, 'United States', 'Newark', 1874.09);
insert into holiday (id, country, city, price) values (617, 'Brazil', 'Caldas Novas', 6309.6);
insert into holiday (id, country, city, price) values (618, 'Indonesia', 'Onan Ganjang Satu', 5139.52);
insert into holiday (id, country, city, price) values (619, 'Indonesia', 'Mautapaga Bawah', 7788.69);
insert into holiday (id, country, city, price) values (620, 'Togo', 'Kara', 8576.99);
insert into holiday (id, country, city, price) values (621, 'United States', 'Battle Creek', 9055.89);
insert into holiday (id, country, city, price) values (622, 'China', 'Hekou', 5640.39);
insert into holiday (id, country, city, price) values (623, 'Philippines', 'Mat-i', 6928.09);
insert into holiday (id, country, city, price) values (624, 'Mexico', 'El Mirador', 1008.62);
insert into holiday (id, country, city, price) values (625, 'Sierra Leone', 'Kukuna', 4006.68);
insert into holiday (id, country, city, price) values (626, 'Portugal', 'Belverde', 472.98);
insert into holiday (id, country, city, price) values (627, 'Canada', 'Les Cèdres', 3615.72);
insert into holiday (id, country, city, price) values (628, 'Russia', 'Kulary', 740.23);
insert into holiday (id, country, city, price) values (629, 'Indonesia', 'Banjar Kawan', 8904.52);
insert into holiday (id, country, city, price) values (630, 'Vietnam', 'Phù Mỹ', 8423.57);
insert into holiday (id, country, city, price) values (631, 'France', 'Alençon', 9341.19);
insert into holiday (id, country, city, price) values (632, 'Indonesia', 'Kesambilerenkrajan', 4402.0);
insert into holiday (id, country, city, price) values (633, 'Albania', 'Gostimë', 3509.76);
insert into holiday (id, country, city, price) values (634, 'China', 'Chuzhou', 7746.12);
insert into holiday (id, country, city, price) values (635, 'Russia', 'Shchelkovo', 553.67);
insert into holiday (id, country, city, price) values (636, 'Indonesia', 'Kendayakan', 7988.36);
insert into holiday (id, country, city, price) values (637, 'Serbia', 'Ilandža', 3092.2);
insert into holiday (id, country, city, price) values (638, 'Serbia', 'Stara Pazova', 5328.04);
insert into holiday (id, country, city, price) values (639, 'China', 'Liuhao', 3976.05);
insert into holiday (id, country, city, price) values (640, 'Colombia', 'Elías', 1790.3);
insert into holiday (id, country, city, price) values (641, 'Iran', 'Marāveh Tappeh', 3046.36);
insert into holiday (id, country, city, price) values (642, 'Argentina', 'Valcheta', 885.16);
insert into holiday (id, country, city, price) values (643, 'Serbia', 'Ruma', 3753.01);
insert into holiday (id, country, city, price) values (644, 'Indonesia', 'Cibeusi', 1418.41);
insert into holiday (id, country, city, price) values (645, 'Vietnam', 'Quảng Ngãi', 6249.99);
insert into holiday (id, country, city, price) values (646, 'Spain', 'Madrid', 2577.51);
insert into holiday (id, country, city, price) values (647, 'French Guiana', 'Cayenne', 6228.16);
insert into holiday (id, country, city, price) values (648, 'Malaysia', 'Labuan', 7864.79);
insert into holiday (id, country, city, price) values (649, 'South Korea', 'Cheongju-si', 4539.17);
insert into holiday (id, country, city, price) values (650, 'Honduras', 'Ocote Paulino', 8057.3);
insert into holiday (id, country, city, price) values (651, 'Netherlands', 'Leeuwarden', 906.26);
insert into holiday (id, country, city, price) values (652, 'Philippines', 'Uacon', 5276.03);
insert into holiday (id, country, city, price) values (653, 'Macedonia', 'Извор', 5093.83);
insert into holiday (id, country, city, price) values (654, 'Indonesia', 'Karangtengah', 3762.65);
insert into holiday (id, country, city, price) values (655, 'Indonesia', 'Temenggungan', 3656.97);
insert into holiday (id, country, city, price) values (656, 'Panama', 'Bella Vista', 9069.02);
insert into holiday (id, country, city, price) values (657, 'Paraguay', 'San José', 9813.28);
insert into holiday (id, country, city, price) values (658, 'Philippines', 'Naili', 6096.27);
insert into holiday (id, country, city, price) values (659, 'Poland', 'Chwałowice', 8917.89);
insert into holiday (id, country, city, price) values (660, 'Poland', 'Wróblew', 9312.85);
insert into holiday (id, country, city, price) values (661, 'Brazil', 'Teodoro Sampaio', 9940.21);
insert into holiday (id, country, city, price) values (662, 'Indonesia', 'Cibeureum', 8969.22);
insert into holiday (id, country, city, price) values (663, 'Poland', 'Bielice', 5044.86);
insert into holiday (id, country, city, price) values (664, 'Philippines', 'Sampaloc', 8454.94);
insert into holiday (id, country, city, price) values (665, 'Ireland', 'Ballina', 1333.46);
insert into holiday (id, country, city, price) values (666, 'Uganda', 'Bweyogerere', 8349.39);
insert into holiday (id, country, city, price) values (667, 'Nigeria', 'Kari', 6535.51);
insert into holiday (id, country, city, price) values (668, 'Philippines', 'Cayang', 9621.52);
insert into holiday (id, country, city, price) values (669, 'Sweden', 'Luleå', 6841.63);
insert into holiday (id, country, city, price) values (670, 'China', 'Simapu', 2875.55);
insert into holiday (id, country, city, price) values (671, 'China', 'Jiaocha', 3486.89);
insert into holiday (id, country, city, price) values (672, 'Indonesia', 'Cimalati', 9708.86);
insert into holiday (id, country, city, price) values (673, 'China', 'Fengyuan', 2966.16);
insert into holiday (id, country, city, price) values (674, 'Bulgaria', 'Kula', 7746.69);
insert into holiday (id, country, city, price) values (675, 'France', 'Paris 05', 7924.69);
insert into holiday (id, country, city, price) values (676, 'Brazil', 'Cubatão', 7667.56);
insert into holiday (id, country, city, price) values (677, 'Croatia', 'Ferdinandovac', 6465.1);
insert into holiday (id, country, city, price) values (678, 'Yemen', 'Maţarah', 5096.28);
insert into holiday (id, country, city, price) values (679, 'Mexico', 'Bellavista', 531.19);
insert into holiday (id, country, city, price) values (680, 'Poland', 'Budziszewice', 667.51);
insert into holiday (id, country, city, price) values (681, 'Thailand', 'Sathing Phra', 2379.94);
insert into holiday (id, country, city, price) values (682, 'Poland', 'Łomianki', 6716.4);
insert into holiday (id, country, city, price) values (683, 'Indonesia', 'Limbangan', 1728.24);
insert into holiday (id, country, city, price) values (684, 'China', 'Keluke', 7906.26);
insert into holiday (id, country, city, price) values (685, 'Indonesia', 'Peseng', 2163.86);
insert into holiday (id, country, city, price) values (686, 'Ireland', 'Raphoe', 7078.15);
insert into holiday (id, country, city, price) values (687, 'Poland', 'Gostyń', 1687.17);
insert into holiday (id, country, city, price) values (688, 'Azerbaijan', 'Arıqıran', 1800.65);
insert into holiday (id, country, city, price) values (689, 'Peru', 'Cusco', 1469.56);
insert into holiday (id, country, city, price) values (690, 'Russia', 'Khvalynsk', 2196.28);
insert into holiday (id, country, city, price) values (691, 'El Salvador', 'Ciudad Barrios', 3242.46);
insert into holiday (id, country, city, price) values (692, 'Canada', 'Ajax', 2524.4);
insert into holiday (id, country, city, price) values (693, 'France', 'Paris 07', 359.6);
insert into holiday (id, country, city, price) values (694, 'China', 'Houba', 4657.54);
insert into holiday (id, country, city, price) values (695, 'Kazakhstan', 'Astana', 9977.52);
insert into holiday (id, country, city, price) values (696, 'Afghanistan', 'Ghormach', 7374.22);
insert into holiday (id, country, city, price) values (697, 'Russia', 'Nizhnyaya Tavda', 2110.14);
insert into holiday (id, country, city, price) values (698, 'Costa Rica', 'San Felipe', 5580.93);
insert into holiday (id, country, city, price) values (699, 'Iran', 'Nowshahr', 2700.17);
insert into holiday (id, country, city, price) values (700, 'Ivory Coast', 'Abengourou', 9998.44);
insert into holiday (id, country, city, price) values (701, 'Portugal', 'Soutelo', 4714.02);
insert into holiday (id, country, city, price) values (702, 'China', 'Xiachengzi', 4739.72);
insert into holiday (id, country, city, price) values (703, 'Croatia', 'Pridraga', 9568.16);
insert into holiday (id, country, city, price) values (704, 'Brazil', 'São João da Boa Vista', 2821.19);
insert into holiday (id, country, city, price) values (705, 'China', 'Laojunmiao', 9199.63);
insert into holiday (id, country, city, price) values (706, 'Philippines', 'Jalaud', 8323.78);
insert into holiday (id, country, city, price) values (707, 'Sweden', 'Växjö', 6867.66);
insert into holiday (id, country, city, price) values (708, 'Ukraine', 'Stari Kuty', 3448.5);
insert into holiday (id, country, city, price) values (709, 'Indonesia', 'Margamukti', 5438.01);
insert into holiday (id, country, city, price) values (710, 'Guatemala', 'San Felipe', 6068.34);
insert into holiday (id, country, city, price) values (711, 'China', 'Zhongxing', 7097.24);
insert into holiday (id, country, city, price) values (712, 'China', 'Baga Borihe', 4811.69);
insert into holiday (id, country, city, price) values (713, 'China', 'Sanhe', 7408.19);
insert into holiday (id, country, city, price) values (714, 'Brazil', 'Vargem Grande Paulista', 8551.89);
insert into holiday (id, country, city, price) values (715, 'Russia', 'Demyansk', 8429.02);
insert into holiday (id, country, city, price) values (716, 'Belize', 'San Ignacio', 6852.34);
insert into holiday (id, country, city, price) values (717, 'Colombia', 'Cajicá', 5173.22);
insert into holiday (id, country, city, price) values (718, 'China', 'Feilaixia', 6128.43);
insert into holiday (id, country, city, price) values (719, 'Morocco', 'Al Hoceïma', 1833.68);
insert into holiday (id, country, city, price) values (720, 'United States', 'Roanoke', 2367.29);
insert into holiday (id, country, city, price) values (721, 'China', 'Shishan', 5348.86);
insert into holiday (id, country, city, price) values (722, 'Portugal', 'Valongo', 3102.49);
insert into holiday (id, country, city, price) values (723, 'Sweden', 'Järfälla', 6613.65);
insert into holiday (id, country, city, price) values (724, 'Colombia', 'Momil', 3862.87);
insert into holiday (id, country, city, price) values (725, 'Poland', 'Leśnica', 2592.62);
insert into holiday (id, country, city, price) values (726, 'China', 'Xiaocun', 3244.51);
insert into holiday (id, country, city, price) values (727, 'Russia', 'Novyy Oskol', 267.57);
insert into holiday (id, country, city, price) values (728, 'Russia', 'Dulyapino', 8010.53);
insert into holiday (id, country, city, price) values (729, 'Brazil', 'Tamandaré', 8403.36);
insert into holiday (id, country, city, price) values (730, 'Slovenia', 'Polzela', 642.6);
insert into holiday (id, country, city, price) values (731, 'Mauritania', 'Néma', 3846.04);
insert into holiday (id, country, city, price) values (732, 'Greece', 'Palaiomonástiron', 7564.61);
insert into holiday (id, country, city, price) values (733, 'China', 'Chatian', 5546.25);
insert into holiday (id, country, city, price) values (734, 'Portugal', 'Baganha', 9085.63);
insert into holiday (id, country, city, price) values (735, 'Indonesia', 'Nunsena', 4535.6);
insert into holiday (id, country, city, price) values (736, 'Armenia', 'Spitak', 6856.44);
insert into holiday (id, country, city, price) values (737, 'Indonesia', 'Bajomulyo', 1173.59);
insert into holiday (id, country, city, price) values (738, 'Lithuania', 'Jieznas', 2874.62);
insert into holiday (id, country, city, price) values (739, 'Argentina', '28 de Noviembre', 9720.96);
insert into holiday (id, country, city, price) values (740, 'Russia', 'Radovitskiy', 5094.42);
insert into holiday (id, country, city, price) values (741, 'Canada', 'Belleville', 181.02);
insert into holiday (id, country, city, price) values (742, 'Honduras', 'Concordia', 183.03);
insert into holiday (id, country, city, price) values (743, 'Nigeria', 'Ifon', 4148.43);
insert into holiday (id, country, city, price) values (744, 'Russia', 'Borisovka', 3356.25);
insert into holiday (id, country, city, price) values (745, 'Mongolia', 'Darhan', 4021.95);
insert into holiday (id, country, city, price) values (746, 'Panama', 'Ustupo', 4259.51);
insert into holiday (id, country, city, price) values (747, 'Russia', 'Dvurechensk', 7080.5);
insert into holiday (id, country, city, price) values (748, 'Poland', 'Dębowiec', 9845.8);
insert into holiday (id, country, city, price) values (749, 'Peru', 'Coris', 6226.06);
insert into holiday (id, country, city, price) values (750, 'Brazil', 'Campos Novos', 8023.51);
insert into holiday (id, country, city, price) values (751, 'Indonesia', 'Malimaneek', 3420.51);
insert into holiday (id, country, city, price) values (752, 'United States', 'Biloxi', 1501.97);
insert into holiday (id, country, city, price) values (753, 'Pakistan', 'Sehwān', 7208.39);
insert into holiday (id, country, city, price) values (754, 'Indonesia', 'Somorpenang', 1719.4);
insert into holiday (id, country, city, price) values (755, 'Canada', 'Newmarket', 6074.63);
insert into holiday (id, country, city, price) values (756, 'Greece', 'Stylída', 9423.14);
insert into holiday (id, country, city, price) values (757, 'French Polynesia', 'Arue', 9134.8);
insert into holiday (id, country, city, price) values (758, 'Philippines', 'Sabang', 3194.46);
insert into holiday (id, country, city, price) values (759, 'Russia', 'Cherëmukhovo', 7498.06);
insert into holiday (id, country, city, price) values (760, 'Belgium', 'Bruxelles', 5996.25);
insert into holiday (id, country, city, price) values (761, 'Indonesia', 'Gununglajang', 7748.53);
insert into holiday (id, country, city, price) values (762, 'Uruguay', 'San Bautista', 7505.25);
insert into holiday (id, country, city, price) values (763, 'Indonesia', 'Terara', 5266.49);
insert into holiday (id, country, city, price) values (764, 'Portugal', 'Rio de Moinhos', 7436.11);
insert into holiday (id, country, city, price) values (765, 'Brazil', 'Campos do Jordão', 2572.89);
insert into holiday (id, country, city, price) values (766, 'Portugal', 'Vilar do Monte', 1954.56);
insert into holiday (id, country, city, price) values (767, 'Philippines', 'Tagakpan', 6369.98);
insert into holiday (id, country, city, price) values (768, 'Colombia', 'Barbosa', 7506.88);
insert into holiday (id, country, city, price) values (769, 'China', 'Fangyan', 8749.87);
insert into holiday (id, country, city, price) values (770, 'Indonesia', 'Banjarejo', 466.25);
insert into holiday (id, country, city, price) values (771, 'France', 'Paris 08', 7857.78);
insert into holiday (id, country, city, price) values (772, 'Czech Republic', 'Havlíčkův Brod', 6021.59);
insert into holiday (id, country, city, price) values (773, 'Ukraine', 'Korop', 4540.1);
insert into holiday (id, country, city, price) values (774, 'Democratic Republic of the Congo', 'Demba', 8740.62);
insert into holiday (id, country, city, price) values (775, 'China', 'Tongjiaxi', 4781.97);
insert into holiday (id, country, city, price) values (776, 'Philippines', 'Dolo', 298.3);
insert into holiday (id, country, city, price) values (777, 'China', 'Magutian', 2071.13);
insert into holiday (id, country, city, price) values (778, 'China', 'Shuanghe', 9761.55);
insert into holiday (id, country, city, price) values (779, 'Honduras', 'Las Vegas', 6452.38);
insert into holiday (id, country, city, price) values (780, 'Democratic Republic of the Congo', 'Yangambi', 2719.38);
insert into holiday (id, country, city, price) values (781, 'Ukraine', 'Klevan’', 1628.22);
insert into holiday (id, country, city, price) values (782, 'Indonesia', 'Temuji', 5306.9);
insert into holiday (id, country, city, price) values (783, 'Saudi Arabia', 'Khamis Mushait', 825.85);
insert into holiday (id, country, city, price) values (784, 'Croatia', 'Omiš', 5228.09);
insert into holiday (id, country, city, price) values (785, 'Venezuela', 'Clarines', 9800.2);
insert into holiday (id, country, city, price) values (786, 'Russia', 'Novopavlovsk', 7515.38);
insert into holiday (id, country, city, price) values (787, 'Indonesia', 'Lalukoen Dua', 6072.37);
insert into holiday (id, country, city, price) values (788, 'France', 'Mazamet', 708.71);
insert into holiday (id, country, city, price) values (789, 'Iran', 'Tajrīsh', 9497.03);
insert into holiday (id, country, city, price) values (790, 'Azerbaijan', 'Naftalan', 6176.28);
insert into holiday (id, country, city, price) values (791, 'Libya', 'Gharyan', 8689.27);
insert into holiday (id, country, city, price) values (792, 'Mexico', 'Hidalgo', 9793.29);
insert into holiday (id, country, city, price) values (793, 'Indonesia', 'Timurlorong', 143.58);
insert into holiday (id, country, city, price) values (794, 'China', 'Jidong', 6277.98);
insert into holiday (id, country, city, price) values (795, 'Indonesia', 'Rado', 4023.82);
insert into holiday (id, country, city, price) values (796, 'Philippines', 'Conduaga', 1360.79);
insert into holiday (id, country, city, price) values (797, 'Indonesia', 'Talondang', 6358.78);
insert into holiday (id, country, city, price) values (798, 'Canada', 'Richmond', 4358.78);
insert into holiday (id, country, city, price) values (799, 'Finland', 'Pernå', 1335.38);
insert into holiday (id, country, city, price) values (800, 'China', 'Nankou', 3699.72);
insert into holiday (id, country, city, price) values (801, 'China', 'Jincheng', 1762.71);
insert into holiday (id, country, city, price) values (802, 'Portugal', 'São Bartolomeu', 4548.76);
insert into holiday (id, country, city, price) values (803, 'Thailand', 'Phon Phisai', 5210.91);
insert into holiday (id, country, city, price) values (804, 'Japan', 'Asahi', 6284.52);
insert into holiday (id, country, city, price) values (805, 'China', 'Lujing Zhen', 3438.96);
insert into holiday (id, country, city, price) values (806, 'Lesotho', 'Quthing', 9999.31);
insert into holiday (id, country, city, price) values (807, 'Poland', 'Kobiernice', 8141.28);
insert into holiday (id, country, city, price) values (808, 'Poland', 'Rączna', 5962.66);
insert into holiday (id, country, city, price) values (809, 'Indonesia', 'Sipoholon', 3097.54);
insert into holiday (id, country, city, price) values (810, 'Syria', 'Al Quţayfah', 4972.73);
insert into holiday (id, country, city, price) values (811, 'China', 'A’yi Take', 9977.44);
insert into holiday (id, country, city, price) values (812, 'Thailand', 'Siao', 5166.02);
insert into holiday (id, country, city, price) values (813, 'Indonesia', 'Oibioin', 9210.59);
insert into holiday (id, country, city, price) values (814, 'China', 'Liugou', 4032.57);
insert into holiday (id, country, city, price) values (815, 'Indonesia', 'Tanahmerah', 7892.07);
insert into holiday (id, country, city, price) values (816, 'Philippines', 'Linoan', 5374.15);
insert into holiday (id, country, city, price) values (817, 'Canada', 'Thompson', 5523.07);
insert into holiday (id, country, city, price) values (818, 'Canada', 'Morinville', 4162.74);
insert into holiday (id, country, city, price) values (819, 'United States', 'Sterling', 4220.56);
insert into holiday (id, country, city, price) values (820, 'China', 'Zoumaping', 3809.9);
insert into holiday (id, country, city, price) values (821, 'Argentina', 'Río Segundo', 7140.94);
insert into holiday (id, country, city, price) values (822, 'Mongolia', 'Örgön', 3517.67);
insert into holiday (id, country, city, price) values (823, 'Morocco', 'Riah', 1536.24);
insert into holiday (id, country, city, price) values (824, 'China', 'Yuncheng', 8021.34);
insert into holiday (id, country, city, price) values (825, 'Indonesia', 'Dengok', 386.0);
insert into holiday (id, country, city, price) values (826, 'Bosnia and Herzegovina', 'Orahovica Donja', 6742.68);
insert into holiday (id, country, city, price) values (827, 'Philippines', 'Bilar', 5228.51);
insert into holiday (id, country, city, price) values (828, 'Brazil', 'Lagoa da Prata', 8141.65);
insert into holiday (id, country, city, price) values (829, 'Russia', 'Vladimir', 4475.87);
insert into holiday (id, country, city, price) values (830, 'Portugal', 'Calde', 3529.47);
insert into holiday (id, country, city, price) values (831, 'Nigeria', 'Monguno', 6528.76);
insert into holiday (id, country, city, price) values (832, 'France', 'Besançon', 1612.98);
insert into holiday (id, country, city, price) values (833, 'Portugal', 'Estombar', 442.55);
insert into holiday (id, country, city, price) values (834, 'Brazil', 'Santa Rosa de Viterbo', 3493.25);
insert into holiday (id, country, city, price) values (835, 'Poland', 'Regulice', 7710.86);
insert into holiday (id, country, city, price) values (836, 'Uganda', 'Otuke', 1279.03);
insert into holiday (id, country, city, price) values (837, 'Nepal', 'Dhangarhi', 6606.0);
insert into holiday (id, country, city, price) values (838, 'China', 'Puqian', 2717.78);
insert into holiday (id, country, city, price) values (839, 'Ukraine', 'Kodra', 4298.31);
insert into holiday (id, country, city, price) values (840, 'France', 'Mont-de-Marsan', 4033.11);
insert into holiday (id, country, city, price) values (841, 'United States', 'Marietta', 9278.54);
insert into holiday (id, country, city, price) values (842, 'United States', 'Van Nuys', 1676.52);
insert into holiday (id, country, city, price) values (843, 'Colombia', 'Acacías', 187.74);
insert into holiday (id, country, city, price) values (844, 'Luxembourg', 'Crauthem', 7369.45);
insert into holiday (id, country, city, price) values (845, 'Philippines', 'Balaoang', 8206.44);
insert into holiday (id, country, city, price) values (846, 'Philippines', 'San Juan de Mata', 9337.32);
insert into holiday (id, country, city, price) values (847, 'China', 'Taiyuan', 8111.59);
insert into holiday (id, country, city, price) values (848, 'Sweden', 'Kvänum', 8690.49);
insert into holiday (id, country, city, price) values (849, 'China', 'Pingtian', 2482.61);
insert into holiday (id, country, city, price) values (850, 'China', 'Taohua', 5785.28);
insert into holiday (id, country, city, price) values (851, 'China', 'Lin’an', 6175.09);
insert into holiday (id, country, city, price) values (852, 'Mexico', 'Santa Maria', 2714.48);
insert into holiday (id, country, city, price) values (853, 'China', 'Wenfang', 9470.36);
insert into holiday (id, country, city, price) values (854, 'Iran', 'Malāyer', 9441.39);
insert into holiday (id, country, city, price) values (855, 'New Caledonia', 'Pouébo', 6244.28);
insert into holiday (id, country, city, price) values (856, 'Peru', 'Cuchumbaya', 5086.5);
insert into holiday (id, country, city, price) values (857, 'China', 'Dengfang', 2936.7);
insert into holiday (id, country, city, price) values (858, 'Portugal', 'Algés', 6263.08);
insert into holiday (id, country, city, price) values (859, 'China', 'Huipinggeng', 3536.04);
insert into holiday (id, country, city, price) values (860, 'Sweden', 'Kumla', 2440.23);
insert into holiday (id, country, city, price) values (861, 'United States', 'Knoxville', 2475.33);
insert into holiday (id, country, city, price) values (862, 'Portugal', 'Zambujeira', 8639.03);
insert into holiday (id, country, city, price) values (863, 'Russia', 'Orekhovo-Zuyevo', 6961.59);
insert into holiday (id, country, city, price) values (864, 'Russia', 'Mnogoudobnoye', 3856.1);
insert into holiday (id, country, city, price) values (865, 'Finland', 'Valkeakoski', 8140.03);
insert into holiday (id, country, city, price) values (866, 'Peru', 'Cochabamba', 9819.76);
insert into holiday (id, country, city, price) values (867, 'Portugal', 'Lagoa', 6369.02);
insert into holiday (id, country, city, price) values (868, 'Somalia', 'Dujuuma', 6877.99);
insert into holiday (id, country, city, price) values (869, 'China', 'Yanggang', 9271.87);
insert into holiday (id, country, city, price) values (870, 'Bosnia and Herzegovina', 'Liješnica', 7928.66);
insert into holiday (id, country, city, price) values (871, 'Philippines', 'Mabilog', 521.52);
insert into holiday (id, country, city, price) values (872, 'Thailand', 'Yaring', 6182.88);
insert into holiday (id, country, city, price) values (873, 'United States', 'Washington', 1364.26);
insert into holiday (id, country, city, price) values (874, 'Indonesia', 'Gumawang', 8389.21);
insert into holiday (id, country, city, price) values (875, 'Argentina', 'Belén de Escobar', 6264.26);
insert into holiday (id, country, city, price) values (876, 'Mexico', 'Rancho Nuevo', 9707.2);
insert into holiday (id, country, city, price) values (877, 'Panama', 'Caimitillo', 2319.9);
insert into holiday (id, country, city, price) values (878, 'Portugal', 'Póvoa', 1521.64);
insert into holiday (id, country, city, price) values (879, 'China', 'Jijia', 6042.64);
insert into holiday (id, country, city, price) values (880, 'Iraq', '‘Alī al Gharbī', 6238.5);
insert into holiday (id, country, city, price) values (881, 'Mexico', 'Los Angeles', 2963.94);
insert into holiday (id, country, city, price) values (882, 'China', 'Wenshang', 4719.48);
insert into holiday (id, country, city, price) values (883, 'China', 'Guangli', 2641.97);
insert into holiday (id, country, city, price) values (884, 'Egypt', 'Fāqūs', 9447.5);
insert into holiday (id, country, city, price) values (885, 'China', 'Baozi', 3606.45);
insert into holiday (id, country, city, price) values (886, 'Indonesia', 'Blimbing', 3578.98);
insert into holiday (id, country, city, price) values (887, 'Netherlands', 'Dordrecht', 6464.2);
insert into holiday (id, country, city, price) values (888, 'Russia', 'Nevel’sk', 2576.44);
insert into holiday (id, country, city, price) values (889, 'Peru', 'Huayllabamba', 5223.44);
insert into holiday (id, country, city, price) values (890, 'China', 'Qiaoxia', 7525.14);
insert into holiday (id, country, city, price) values (891, 'Brazil', 'Nova Odessa', 2197.52);
insert into holiday (id, country, city, price) values (892, 'Chile', 'Calbuco', 7749.16);
insert into holiday (id, country, city, price) values (893, 'Ukraine', 'Arbuzynka', 8471.13);
insert into holiday (id, country, city, price) values (894, 'Trinidad and Tobago', 'Mucurapo', 9690.36);
insert into holiday (id, country, city, price) values (895, 'China', 'Shimen', 454.04);
insert into holiday (id, country, city, price) values (896, 'China', 'Xinfu', 3057.23);
insert into holiday (id, country, city, price) values (897, 'Japan', 'Shinjō', 3014.62);
insert into holiday (id, country, city, price) values (898, 'France', 'Balma', 9682.14);
insert into holiday (id, country, city, price) values (899, 'China', 'Daogao', 8751.28);
insert into holiday (id, country, city, price) values (900, 'Ireland', 'Donabate', 6448.25);
insert into holiday (id, country, city, price) values (901, 'Russia', 'Debesy', 7678.29);
insert into holiday (id, country, city, price) values (902, 'Czech Republic', 'Stará Paka', 7376.89);
insert into holiday (id, country, city, price) values (903, 'Indonesia', 'Sayang Lauq', 4830.6);
insert into holiday (id, country, city, price) values (904, 'Brazil', 'Mateus Leme', 9904.55);
insert into holiday (id, country, city, price) values (905, 'Indonesia', 'Pontang Tengah', 4793.43);
insert into holiday (id, country, city, price) values (906, 'Russia', 'Odesskoye', 2322.37);
insert into holiday (id, country, city, price) values (907, 'Colombia', 'Flandes', 2058.63);
insert into holiday (id, country, city, price) values (908, 'Japan', 'Okegawa', 9737.47);
insert into holiday (id, country, city, price) values (909, 'Sweden', 'Laholm', 3695.83);
insert into holiday (id, country, city, price) values (910, 'Philippines', 'Wawa', 2151.36);
insert into holiday (id, country, city, price) values (911, 'Indonesia', 'Cigintung', 7239.64);
insert into holiday (id, country, city, price) values (912, 'Poland', 'Jastrzębia Góra', 760.26);
insert into holiday (id, country, city, price) values (913, 'New Zealand', 'Paihia', 116.08);
insert into holiday (id, country, city, price) values (914, 'Indonesia', 'Datar', 7643.65);
insert into holiday (id, country, city, price) values (915, 'Japan', 'Ushibuka', 3406.54);
insert into holiday (id, country, city, price) values (916, 'China', 'Xiashixiang', 3482.33);
insert into holiday (id, country, city, price) values (917, 'China', 'Pingyao', 4159.78);
insert into holiday (id, country, city, price) values (918, 'Indonesia', 'Sumurnanjung', 4508.33);
insert into holiday (id, country, city, price) values (919, 'Ukraine', 'Nyzhnya Krynka', 4889.26);
insert into holiday (id, country, city, price) values (920, 'Democratic Republic of the Congo', 'Demba', 1805.73);
insert into holiday (id, country, city, price) values (921, 'Dominican Republic', 'Río Grande', 9960.95);
insert into holiday (id, country, city, price) values (922, 'Nigeria', 'Ngala', 6845.52);
insert into holiday (id, country, city, price) values (923, 'Philippines', 'Silae', 5433.96);
insert into holiday (id, country, city, price) values (924, 'Bosnia and Herzegovina', 'Podhum', 8236.63);
insert into holiday (id, country, city, price) values (925, 'Indonesia', 'Bantu', 1557.15);
insert into holiday (id, country, city, price) values (926, 'France', 'Morez', 1407.36);
insert into holiday (id, country, city, price) values (927, 'China', 'Shenshu', 2710.52);
insert into holiday (id, country, city, price) values (928, 'Japan', 'Koga', 5688.46);
insert into holiday (id, country, city, price) values (929, 'France', 'Saint-Claude', 6881.93);
insert into holiday (id, country, city, price) values (930, 'Russia', 'Kantyshevo', 2291.63);
insert into holiday (id, country, city, price) values (931, 'Indonesia', 'Cungkal', 3687.71);
insert into holiday (id, country, city, price) values (932, 'China', 'Baisha', 341.44);
insert into holiday (id, country, city, price) values (933, 'Indonesia', 'Pasirlimus', 3029.06);
insert into holiday (id, country, city, price) values (934, 'Croatia', 'Tenja', 1922.11);
insert into holiday (id, country, city, price) values (935, 'Guatemala', 'Santa María Ixhuatán', 7784.85);
insert into holiday (id, country, city, price) values (936, 'Serbia', 'Lok', 7458.19);
insert into holiday (id, country, city, price) values (937, 'Indonesia', 'Krajan Sidodadi', 3943.03);
insert into holiday (id, country, city, price) values (938, 'Indonesia', 'Ngrejo', 4283.02);
insert into holiday (id, country, city, price) values (939, 'China', 'Bijia', 6596.07);
insert into holiday (id, country, city, price) values (940, 'Philippines', 'Hinigaran', 8115.86);
insert into holiday (id, country, city, price) values (941, 'Dominican Republic', 'Duvergé', 8897.58);
insert into holiday (id, country, city, price) values (942, 'United States', 'Beaumont', 1769.23);
insert into holiday (id, country, city, price) values (943, 'Philippines', 'Perez', 5293.65);
insert into holiday (id, country, city, price) values (944, 'China', 'Jingdezhen', 8032.27);
insert into holiday (id, country, city, price) values (945, 'China', 'Hadabei', 8865.91);
insert into holiday (id, country, city, price) values (946, 'China', 'Sanlanbahai', 1506.9);
insert into holiday (id, country, city, price) values (947, 'United States', 'Pensacola', 2504.21);
insert into holiday (id, country, city, price) values (948, 'China', 'Linhu', 2338.72);
insert into holiday (id, country, city, price) values (949, 'China', 'Huangzhuang', 323.82);
insert into holiday (id, country, city, price) values (950, 'Argentina', 'Quilino', 2077.13);
insert into holiday (id, country, city, price) values (951, 'United States', 'Oklahoma City', 5299.58);
insert into holiday (id, country, city, price) values (952, 'Jamaica', 'May Pen', 6005.2);
insert into holiday (id, country, city, price) values (953, 'Colombia', 'Quípama', 9477.74);
insert into holiday (id, country, city, price) values (954, 'China', 'Nancaicun', 7928.6);
insert into holiday (id, country, city, price) values (955, 'Argentina', 'Laborde', 5096.64);
insert into holiday (id, country, city, price) values (956, 'Ghana', 'Mamponteng', 2211.02);
insert into holiday (id, country, city, price) values (957, 'China', 'Hetou', 4649.55);
insert into holiday (id, country, city, price) values (958, 'China', 'Huangqi', 6270.53);
insert into holiday (id, country, city, price) values (959, 'Ukraine', 'Yasinya', 1402.4);
insert into holiday (id, country, city, price) values (960, 'China', 'Shuangmiaojie', 2799.59);
insert into holiday (id, country, city, price) values (961, 'Canada', 'Burnaby', 7537.49);
insert into holiday (id, country, city, price) values (962, 'Indonesia', 'Mojo', 2061.66);
insert into holiday (id, country, city, price) values (963, 'China', 'Yongdeng Chengguanzhen', 7695.62);
insert into holiday (id, country, city, price) values (964, 'Argentina', 'Albardón', 3567.3);
insert into holiday (id, country, city, price) values (965, 'Indonesia', 'Lajarik', 2604.8);
insert into holiday (id, country, city, price) values (966, 'Ukraine', 'Balaklava', 5046.0);
insert into holiday (id, country, city, price) values (967, 'Mongolia', 'Baruunsuu', 4890.25);
insert into holiday (id, country, city, price) values (968, 'Brazil', 'Aquidauana', 1742.78);
insert into holiday (id, country, city, price) values (969, 'Honduras', 'La Jutosa', 1400.73);
insert into holiday (id, country, city, price) values (970, 'China', 'Datong', 7828.37);
insert into holiday (id, country, city, price) values (971, 'Indonesia', 'Sekarjalak', 1064.77);
insert into holiday (id, country, city, price) values (972, 'Indonesia', 'Kojagete', 3675.27);
insert into holiday (id, country, city, price) values (973, 'United States', 'Minneapolis', 5269.81);
insert into holiday (id, country, city, price) values (974, 'Palau', 'Sonsorol Village', 490.49);
insert into holiday (id, country, city, price) values (975, 'China', 'Changgou', 5952.93);
insert into holiday (id, country, city, price) values (976, 'Czech Republic', 'Újezd', 6682.05);
insert into holiday (id, country, city, price) values (977, 'Australia', 'Eastern Suburbs Mc', 3594.23);
insert into holiday (id, country, city, price) values (978, 'Indonesia', 'Rancageneng Satu', 7926.02);
insert into holiday (id, country, city, price) values (979, 'China', 'Hainan', 5024.67);
insert into holiday (id, country, city, price) values (980, 'China', 'Jiangnan', 3313.82);
insert into holiday (id, country, city, price) values (981, 'Russia', 'Kraskino', 438.4);
insert into holiday (id, country, city, price) values (982, 'Cape Verde', 'Ribeira Grande', 9346.21);
insert into holiday (id, country, city, price) values (983, 'Norway', 'Halden', 9398.06);
insert into holiday (id, country, city, price) values (984, 'Jamaica', 'Mocho', 5618.5);
insert into holiday (id, country, city, price) values (985, 'Bulgaria', 'Bukhovo', 2431.03);
insert into holiday (id, country, city, price) values (986, 'United States', 'Oklahoma City', 5170.82);
insert into holiday (id, country, city, price) values (987, 'Czech Republic', 'Zdounky', 5397.19);
insert into holiday (id, country, city, price) values (988, 'China', 'Yanling', 9789.36);
insert into holiday (id, country, city, price) values (989, 'Israel', 'Rumat Heib', 8314.51);
insert into holiday (id, country, city, price) values (990, 'United States', 'Bakersfield', 238.12);
insert into holiday (id, country, city, price) values (991, 'El Salvador', 'Texistepeque', 4638.9);
insert into holiday (id, country, city, price) values (992, 'China', 'Donghe', 1919.95);
insert into holiday (id, country, city, price) values (993, 'Poland', 'Niedrzwica Duża', 5660.55);
insert into holiday (id, country, city, price) values (994, 'Russia', 'Baryshevo', 866.81);
insert into holiday (id, country, city, price) values (995, 'Indonesia', 'Aemura', 8559.48);
insert into holiday (id, country, city, price) values (996, 'China', 'Yuecheng', 1980.12);
insert into holiday (id, country, city, price) values (997, 'Portugal', 'Pontinha', 3602.52);
insert into holiday (id, country, city, price) values (998, 'Indonesia', 'Sobontoro', 8840.12);
insert into holiday (id, country, city, price) values (999, 'Denmark', 'København', 3722.05);
insert into holiday (id, country, city, price) values (1000, 'Russia', 'Edissiya', 9648.51);
